services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flickd-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/outputs:/app/backend/outputs
      - ./backend/models:/app/backend/models
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flickd-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

    env_file:
      - .env
