services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: flickd-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: flickd-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

    env_file:
      - .env
